job_template: &template
  working_directory: &workdir /tmp/readyblocks-node
  docker:
    - image: circleci/node:8.10

workspace: &attach
  attach_workspace:
      at: *workdir

version: 2
jobs:
  build:
    <<: *template
    steps:
      - checkout

      # restore cached dependencies
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies- # fall back to the latest available cache

      - run:
          name: Install dependencies
          command: yarn install --non-interactive

      # save the dependencies to the cache
      - save_cache:
          paths:
            - node_modules/
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Build the module
          command: yarn build

      # save the dependencies for downstream jobs
      - persist_to_workspace:
          root: *workdir
          paths:
            - .

  artifact:
    <<: *template
    steps:
      - *attach

      - run:
          name: Bundle the module into a Zip file
          command: zip -r dist.zip dist/

      - run:
          name: Bundle the module into a gzipped tar file
          command: tar czf dist.tar.gz dist/

      - store_artifacts:
          path: dist.zip
          destination: module

      - store_artifacts:
          path: dist.tar.gz
          destination: module

  test:
    <<: *template
    steps:
      - *attach

      - run:
          name: Test the module
          command: yarn test

      - persist_to_workspace:
          root: *workdir
          paths:
            - .nyc_output/
  
  coverage:
    <<: *template
    steps:
      - *attach
      
      - run:
          name: Upload test coverage reports
          command: yarn coverage
  
  release:
    <<: *template
    steps:
      - *attach

      - run:
          name: Upload the module to GitHub releases
          command: echo "Not implemented yet"

  deploy:
    <<: *template
    steps:
      - *attach

      - run:
          name: Package and upload the module to npm
          command: echo "Not implemented yet"

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - artifact:
          requires:
            - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - test
      - release:
          filters:
            branches:
              only:
                - master
            tags:
              only: /.+/
          requires:
            - test
      - deploy:
          filters:
            branches:
              only:
                - master
            tags:
              only: /.+/
          requires:
            - test